### ISSUE TITLE
Add a vignette with comparisons

### ISSUE THREAD

**Issue by jolars** [straw-boy/solvers#7]
Add a vignette (using `usethis::use_vignette()`) to start creating benchmarks for the various solvers.

**Comment by straw-boy** [comment]
What do you have in mind when we talk about creating a benchmark? I am thinking of generating some dataset and printing the time taken by the two solvers for each of the `alpha` value in the regularization path.

**Comment by jolars** [comment]
Yes, but it is also a good idea to keep track of the objective during each run of solver so that you we can plot the progress.

**Comment by straw-boy** [comment]
Shall I write R functions to plot the objective vs iterations given the fit though, say solvers::FISTA() ? Also, if yes, plot has to be of a specific value of `alpha`.

**Comment by jolars** [comment]
No, you don't need to write a separate function. Just include a `diagnostics` argument in the `FISTA()` function to specify that you want to record progress (or just always do so) so that you can retrieve it afterwards.

Something like this is what I have in mind: <https://github.com/jolars/slopesolvers/blob/master/vignettes/binomial.Rmd>

**Comment by straw-boy** [comment]
Added in Pull request #10 . Have to see how to increase size of plot (hence keeping this open).

**Comment by jolars** [comment]
```{r, fig.width = 5, fig.height = 5}
plot(x, y)
```
