### ISSUE TITLE
Add a pkgdown site for the project

### ISSUE THREAD

**Issue by jolars** [straw-boy/solvers#8]
Add a pkgdown site for this project. This will make it easy to see the results of the benchmarks and have them update automatically as the package is developed. 

See <https://pkgdown.r-lib.org/index.html> for more info. 

Use `usethis::use_pkgdown()` to start using pkgdown.

**Comment by straw-boy** [comment]
An active site has been deployed at [https://straw-boy.github.io/solvers/](https://straw-boy.github.io/solvers/) . At the moment, I have set manual deployment using master/docs

**Comment by straw-boy** [comment]
I'll soon set up travis-ci for automatic updation.

**Comment by jolars** [comment]
You've already setup github actions to push the pkgdown site? https://github.com/straw-boy/solvers/actions?query=workflow%3Apkgdown

**Comment by straw-boy** [comment]
Doesn't this require _pkgdown.ylm file? I am not sure what to write in it. All the documentations seem to be pointing at setting up travis.yml.

**Comment by straw-boy** [comment]
I don't know what the problem was, but it seems to be working now.
